### ISSUE TITLE
full-text search

### ISSUE THREAD

**Issue by Fanni-Portier** [heimrichhannot/contao-events-bundle#10]
Is it possible to implement a full-text search for events with this extension?

**Comment by koertho** [comment]
@Fanni-Portier No, a full text search is already included in contao.

**Comment by Fanni-Portier** [comment]
@koertho 
Yes, of course, but i am looking for a way to search only inside events AND use the events templates for the output.
I think a combination of search and events templates will be quite complicated.

**Comment by koertho** [comment]
@Fanni-Portier If you like to experiment, you can try out [filter-bundle](https://github.com/heimrichhannot/contao-filter-bundle), this has a text search for dca tables.
But the events-bundle has no such function.

**Comment by Fanni-Portier** [comment]
Thank you!
