### ISSUE TITLE
Contact and location legend shown multiple times

### ISSUE THREAD

**Issue by manjarco** [heimrichhannot/contao-events-bundle#4]
Contao 4.9.16
Events-Bundle 1.6.0

There are some issues with kmielke/calendar-extended-bundle, where the contact legend and location legend and their fields are shown multiple times. But that might very well be calendar-extended’s issue… (and doesn’t bother me right now personally).

![Bildschirmfoto 2021-07-05 um 16 58 16](https://user-images.githubusercontent.com/274524/124490311-3949ff00-ddb2-11eb-870d-9632e8fd8c94.png)

**Comment by koertho** [comment]
I'm closing this in favor of #7
