### ISSUE TITLE
Palette defekt

### ISSUE THREAD

**Issue by pbd-kn** [heimrichhannot/contao-events-bundle#7]
Contao 4.9
contao-event-bundle 1.7.0
kmielke/calendar-extended-bundle 1.0.15

Beim erzeugen eines neuen Events ist die palette zerstört ({contact_legend)
Die Anzeige Kontakt und rtsangaben erscheint mehrfch und kann nicht eingeklappt werden.

Screenshot

![Fehlerhafte Palette](https://user-images.githubusercontent.com/75879364/146825961-30a6485b-90b1-471b-97c8-3fcbb8082b0a.png)
t

**Comment by koertho** [comment]
Hi, ich habe das Bundle gerade mal in einem "sauberen" Contao installiert, da tritt der Fehler nicht auf. Allerdings überschneiden sich die beiden Bundles, die du installiert hast, beide haben eine contact_legend und eine location_legend. Bei unserem sind beide Legenden zumindest in deutsch korrekt übersetzt. Wie es bei dem anderen ist, weiß ich nicht. Aufgrund der Überschneidung solltest du aber nicht beide installieren

**Comment by koertho** [comment]
Der Fehler wurde übrigens auch schon in #4 reported

**Comment by koertho** [comment]
Ich habe gerade eine neue Version 1.7.1 getaggt, wo es nun zumindest von unserer Seite keine doppelungen mehr geben sollte. Der Paletten-Anpassungscode war nicht ganz korrekt, das habe ich korrigiert.
